export * from "./Main/Main"
export * from "./Header/Header"
export * from "./TypePokemonsPage/TypePokemonsPage"
export * from "./Home/Home"
export * from "./SearchPage/SearchPage"
export * from "./AbilityPokemonsPage/AbilityPokemonsPage"
export * from "./PokemonsPage/PokemonsPage"